Add packager for FIS specific ISO spec
teamforage/iso-8583-socket-queue pull request #1
Opened 2021-07-23 22:55 UTC by ForageRob

Need to set useHeader to False for FIS messaging.

I changed the lib/iso8583/packer/ans.js file so that it no longer works with the other packager classes (i.e. openWay.js and smartVista.js).

Added a new packer for x + n data that hasn't existed before.

2021-07-26 18:30 UTC, tuxtitlan requested changes

2021-07-26 18:30 UTC, tuxtitlan commented on lib/iso8583/lib/packer/xn.js
> +  exports.unpack = function(msg, packager) {
nitpick: inconsistent indentation

2021-07-26 18:30 UTC, tuxtitlan commented on lib/iso8583/lib/packager/fis.js
> +exports.format = {
This full list of data elements is awesome

2021-07-26 18:30 UTC, tuxtitlan commented on lib/iso8583/lib/packager/fis.js
> +  obligatoryFields: {
I'm wondering if all message types captured under `Message Formats` (https://docs.google.com/document/d/1KkAAtAFz7O1iqG8p0EKcBBmhr02VEg_2/edit#heading=h.1vsw3ci) should be included here

2021-07-26 18:30 UTC, tuxtitlan commented on lib/iso8583/lib/packager/fis.js
> +  cardholderAuthMethods: {
same here with regards to `PIN Entry Mode Codes (022-2) (Cardholder Verification Method)` (https://docs.google.com/document/d/1KkAAtAFz7O1iqG8p0EKcBBmhr02VEg_2/edit#heading=h.3k3xz3h)

2021-07-26 18:30 UTC, tuxtitlan commented on lib/iso8583/lib/packager/fis.js
> +  cardDataInputModes: {
same here with regards to `PAN Entry Mode Codes (022-1) (Card Reading Method)` (https://docs.google.com/document/d/1KkAAtAFz7O1iqG8p0EKcBBmhr02VEg_2/edit#heading=h.2kz067v)

2021-07-26 22:35 UTC, ForageRob commented on lib/iso8583/lib/packager/fis.js
> +  errors: {
Agreed that we need to modify this logic. I changed `parseInt(code)` to `code.trim()`. Might not be robust enough, but we can revisit this issue later once we can actually test end-to-end.

2021-07-27 16:48 UTC, tuxtitlan commented on lib/iso8583/lib/packager/fis.js
> +    var headerLength = exports.processors.getHeaderLength();
declaration for `getHeaderLength` seems to be missing

2021-07-30 22:18 UTC, tuxtitlan commented on lib/iso8583/lib/packager/fis.js
> +    var headerLength = exports.processors.getHeaderLength();
will be resolved in other PR

2021-07-30 22:19 UTC, tuxtitlan approved these changes

2021-07-30 22:20 UTC, merged